version: '2'
services:
  nginx:
    container_name: 'nginx'
    build:
      context: './'
      dockerfile: './docker/nginx/Dockerfile'
    volumes:
      - ./templates/production:/etc/nginx/templates
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./.env.production
  nodejs:
    container_name: 'backend'
    restart: always
    build:
      context: './'
      dockerfile: './Dockerfile'
  redis:
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
