version: '2'
services:
  redis:
    container_name: redis
    image: redis:6.2.10-alpine
    restart: always
    expose:
      - '6379'
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379
  nginx:
    container_name: nginx
    build:
      context: './'
      dockerfile: './docker/nginx/Dockerfile'
    volumes:
      - ./templates/production:/etc/nginx/templates
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./.env.production
  backend:
    container_name: 'backend'
    restart: always
    build:
      context: './'
      dockerfile: './Dockerfile'
    links:
      - redis
    depends_on:
      - redis
